service: basic-serverless-lambda-python

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

package:
  individually: true

functions:
  theLambda:
    name: TestLambda
    handler: lambda_function.lambda_handler
    description: Lambda para teste
    timeout: 5 
    memorySize: 128
    package:
      patterns:
        - '!src/**'
        - 'src/TestLambda1/**'